version: "3.9"

services:
  deploy:
    image: gbbabarros/rollups-hardhat:0.8.2
    env_file:
      - env.custom.yml
    command:
      [
        "deploy",
        "--network",
        "custom",
        "--export",
        "/opt/cartesi/share/blockchain/custom.json",
      ]
    init: true
    volumes:
      - blockchain-data:/opt/cartesi/share/blockchain
      - ./deployments:/app/rollups/deployments
    network_mode: "host"

volumes:
  blockchain-data: {}