app = "arcanatst"

[build]
image = "registry.fly.io/arcanatst"

[http_service]
internal_port = 10000
force_https = true

[http_service.concurrency]
type = "requests"
soft_limit = 200
hard_limit = 250

[[http_service.checks]]
grace_period = "10s"
interval = "30s"
method = "GET"
timeout = "5s"
path = "/healthz"

[[vm]]
size = "shared-cpu-1x"
memory = "2gb"

[env]
CARTESI_BLOCKCHAIN_FINALITY_OFFSET = "1"
CARTESI_BLOCKCHAIN_ID = "8453"
CARTESI_CONTRACTS_APPLICATION_ADDRESS = "0xf78cf2Eda4b50C38671FbC2A0BcBaDb88208Ce68"
CARTESI_CONTRACTS_AUTHORITY_ADDRESS = "0x7883174aE7D071AcB3eBD174864319a23BA81AEa"
CARTESI_CONTRACTS_HISTORY_ADDRESS = "0x00C941D72d184c9dFe6C5875eb01aC77A619b6D9"
CARTESI_CONTRACTS_INPUT_BOX_ADDRESS = "0x59b22D57D4f067708AB0c00552767405926dc768"
CARTESI_CONTRACTS_INPUT_BOX_DEPLOYMENT_BLOCK_NUMBER = "12987716"
CARTESI_EPOCH_LENGTH = "302400"

